// Tailwind CSS directories
import "./globals.css";

// Custom fonts
import { Inter, Poppins } from "next/font/google";

// Components
import Nav from "./components/layout/Nav";



const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
});
const poppins = Poppins({
  weight: ["400", "500"],
  subsets: ["latin"],
  variable: "--font-poppins",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${poppins.variable}`}
    >
      <body className="w-full overflow-x-hidden">
        <Nav />
        {children}
      </body>
    </html>
  );
}
